import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import BtnBasic from '@components/common/BtnBasic';
import Link from 'next/link';

const Home = () => {
  return (
    <div className={styles.container}>
      {/* <Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1>
					<div className='flex flex-col text-center'>
						<BtnBasic className='bg-yellow-600 text-white'><Link href={'/genbas'}>現場管理</Link></BtnBasic>
					</div>
					<div>
						<BtnBasic>従業員管理</BtnBasic>
					</div>
				</h1>
			</main>

			<footer className={styles.footer}>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
					</span>
				</a>
			</footer> */}
    </div>
  );
};

export default Home;
